#!/bin/bash

make build_monster_unittest
make run_monster_unittest
make build_damage_unittest
make run_damage_unittest
make build_map_unittest
make run_map_unittest
make build_json_unittest
make run_json_unittest
make build_hero_unittest
make run_hero_unittest
make build_game_unittest
make run_game_unittest