name: gtestsflow

on:
  push

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        run: sudo apt install software-properties-common
        run: sudo apt install gcc-7 g++-7 gcc-8 g++-8 gcc-9 g++-9
        run: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 90 --slave /usr/bin/g++ g++ /usr/bin/g++-9 --slave /usr/bin/gcov gcov /usr/bin/gcov-9    
      - name: g++ version info
        run: g++ --version
      - name: Build the program
        run: g++-9 -std=c++17 *.cpp
      - name: Run gtests shell script
        run: chmod +x tests/gtests.sh && ./tests/gtests.sh
