name: gtestsflow

on:
  push

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the program
        run: g++ -std=c++17 *.cpp
      - name: Run gtests shell script
        run: chmod +x tests/gtests.sh && ./tests/gtests.sh
      - name: Run runTests
        run: ./tests/runTests >> tests/gtests_output.txt
      - name: Compare tests/gtests_output.txt with tests/gtests_good_output.txt
        run: diff tests/gtests_output.txt tests/gtests_good_output.txt