name: gtestsflow

on:
  push

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: g++ version info
        run: g++ --version
      - name: Build the program
        run: g++-9 -std=c++17 *.cpp
      - name: Run gtests shell script
        run: chmod +x tests/gtests.sh && ./tests/gtests.sh
