name: Static code analysis

on:
  push

jobs:
  build_and_test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install cppcheck and valgrind
        run: sudo apt install -y cppcheck && sudo apt install -y valgrind 
      - name: Running code analysis with cppcheck
        run: cppcheck *.cpp --enable=all --output-file=cppcheck_output.txt && chmod +x tests/warningcheck.sh && ./tests/warningcheck.sh && chmod +x tests/errorcheck.sh && ./tests/errorcheck.sh
      - name: Upload Cppcheck result 
        uses: actions/upload-artifact@v2  
        with:
          name: cppcheck_output
          path: cppcheck_output.txt
      - name: build
        run: g++-8 -Wall -Werror -Wextra -std=c++17 *.cpp 
      - name: Valgrind check
        run: valgrind --leak-check=full --error-exitcode=1 ./a.out scenarios/scenario1.json
      - name: In-out tests
        run: chmod +x tests/task2.sh && ./tests/task2.sh
