name: Unit tests
on: push
jobs:
  build_and_test:
    runs-on: ubuntu-20.04
    container: vasbeton/unittest_image:latest
    steps:
      - uses: actions/checkout@v2
      - name: cmake
        run: make build_unittest
      - name: Run unit test
        run: make run_unittest
 

  
      
