name: pushdocs workflow

on:
  push:
  
jobs:
  deploy:
    name: Deploy to github pages
    runs-on: ubuntu-latest
    container: vasbeton/doc_image:latest
    steps:
    - uses: actions/checkout@v2

    - name: Push git subdir as branch
      uses: s0/git-publish-subdir-action@v2.4.0

    env:
      REPO: self
      BRANCH: gh-pages
      FOLDER: DOCS/html
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}