name: attackflow.yml

on: 
    push: 
        branches: 
            - attackspeed
            
jobs: 
    build: 
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/chechout@v2
            - run: g++ -std=c++11 *.cpp -o main -w