name: task4 in/out workflow

on:
  push

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the program
        run: g++-8 -std=c++17 *.cpp
      - name: Run task4_inout shell script
        run: ./tests/task4_inout.sh
      - name: Compare native_output1.txt with scenarios/output1.txt
        run: diff native_output1.txt scenarios/output1.txt
      - name: Compare native_output2.txt with scenarios/output2.txt
        run: diff native_output2.txt scenarios/output2.txt
