name: build, static code analysis, leakcheck

on:
  push

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install cppcheck and valgrind
        run: sudo apt install -y cppcheck && sudo apt install -y valgrind && sudo apt install -y gcc g++ 
      - name: Running code analysis with cppcheck
        run: make static_code_analysis
      - name: Upload Cppcheck result 
        uses: actions/upload-artifact@v2  
        with:
          name: cppcheck_output
          path: cppcheck_output.txt
      - name: build
        run: make build
      - name: Valgrind check
        run: make leakcheck
      - name: In-out tests
        run: make io-diff-tests
