name: Unit tests
on: push
jobs:
  build_and_test:
    runs-on: ubuntu-20.04
    container: vasbeton/unittest_image:latest
    steps:
      - uses: actions/checkout@v2
      - name: Build monster tests
        run: make build_monster_unittest
      - name: Run monster tests
        run: make run_monster_unittest
 

  
      
