name: Unit tests
on: push
jobs:
  build_and_test:
    runs-on: ubuntu-20.04
    container: vasbeton/unittest_image:latest
    steps:
      - uses: actions/checkout@v2
      - name: Run unit tests
        run: chmod +x tests/unit_tests_make.sh && ./tests/unit_tests_make.sh
